### ISSUE TITLE
Repo 5 gündür update olunmur

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [AlimaKarimova/PragmatechFoundationProject#31]
Çalışın hər gün update edin.

**Comment by AlimaKarimova** [comment]
Salam Nezrin xanim.men font size ve font weight kimi css-leri bir setre yazmaga calisanda.onlar yaziya tesir gostermir amma ayri ayri yazanda tesir gosterir.ardicilligi duzgun yaziram ne ile elaqedar ola biler sizce.
bir de zehmet olmasa mainproject papkasinda 2.html ve 2.css fayllarima baxa bilersiniz orda timeline yazmisam.her sey duzgun gorunur amma div elave olunanda timeline pozulur

  
>Воскресенье, 2 января 2022, 23:43 +04:00 от Nəzrin İsbəndiyarova ***@***.***>:
> 
> 
>Çalışın hər gün update edin.
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .
>You are receiving this because you are subscribed to this thread. Message ID:  <AlimaKarimova/PragmatechFoundationProject/issues/31 @ github . com> 
 
 
С уважением,
Sunny Way
***@***.***

**Comment by isbendiyarovanezrin** [comment]
Font-size və font-weight'i font-family olmadan birlikdə yazmaq olmaz. Font-weight'i font-size olmadan font-family ilə yazmaq olmaz, amma font-size ilə font-family'ni font-weight olmasa da yazmaq olar.

**Comment by isbendiyarovanezrin** [comment]
"Div" əlavə olunanda pozulursa böyük ehtimal struktur səhv qurulub.

**Comment by isbendiyarovanezrin** [comment]
Gözucu baxdım, məncə, CSS kodlarında problem var. Silib yenidən yazın.

**Comment by AlimaKarimova** [comment]
aha basa dusdum yeqin ki sehvim orda olub

  
>Понедельник, 3 января 2022, 23:48 +04:00 от Nəzrin İsbəndiyarova ***@***.***>:
> 
> 
>Font-size və font-weight'i font-family olmadan birlikdə yazmaq olmaz. Font-weight'i font-size olmadan font-family ilə yazmaq olmaz, amma font-size ilə font-family'ni font-weight olmasa da yazmaq olar.
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .
>You are receiving this because you commented. Message ID:  <AlimaKarimova/PragmatechFoundationProject/issues/31/1004317084 @ github . com>
 
 
С уважением,
Sunny Way
***@***.***
